# Generated by Django 5.0.1 on 2024-01-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="messages",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="GS.message"
            ),
        ),
    ]
