# Generated by Django 5.0.1 on 2024-01-27 03:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GS", "0002_alter_group_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["time"]},
        ),
    ]
