# Generated by Django 5.0.1 on 2024-02-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png",
                height_field="avatar_height",
                upload_to="static/img/avatars",
                width_field="avatar_width",
            ),
        ),
    ]
